### ISSUE TITLE
关于event loop的task 和microtask的问题 求解惑

### ISSUE THREAD

**Issue by webkonglong** [aooy/blog#6]
event loop会不断循环的去取tasks队列的中最老的一个任务推入栈中执行，并在当次循环里依次执行并清空microtask队列里的任务      
--------------------------------------------我是分割线--------------------------------
tasks队列和microtask队列是互相独立的吗？我的理解是  tasks队列执行完毕，然后才会求执行microtask队列。是这样吗？

**Comment by aooy** [comment]
@webkonglong 不是tasks队列执行完毕才执行microtask队列，因为tasks队列里也许会有很多个task任务，是执行完一个task任务就会执行microtask队列。
ps: 可以在文章底下评论，不用另起一个issue。
